### ISSUE TITLE
[Ui/Ux] Site icon + logo

### ISSUE THREAD

**Issue by Justxd22** [Justxd22/tic_tac_toe#3]
- Take amr logo desgin 
- set it as site-icon inside the frontend folder
- set other seo parameters IMP

**Comment by 0x3mr** [comment]
Uploaded the favicon.

**Comment by Justxd22** [comment]
SEO : Search Engine Optimization

Link previews are the snippets of content that appear when you share a URL on social media or messaging platforms. These typically include the page title, description, and an image. You can control how these previews appear using specific HTML tags.

1. Open Graph Tags (For Facebook, LinkedIn, etc.)
Open Graph (OG) tags are widely used to control how links are displayed when shared on platforms like Facebook, LinkedIn, and Twitter.

html
Copy code
<head>
    
    <meta property="og:title" content="Best Hiking Trails in Colorado - Trail Explorer" />

    
    <meta property="og:description" content="Explore the most breathtaking hiking trails in Colorado, complete with stunning views and detailed guides." />

    
    <meta property="og:url" content="https://www.trailexplorer.com/hiking-trails-colorado" />

    
    <meta property="og:image" content="https://www.trailexplorer.com/images/colorado-trail.jpg" />

    
    <meta property="og:site_name" content="Trail Explorer" />

    
    <meta property="og:type" content="website" />
</head>
2. Twitter Cards
Twitter Cards work similarly to Open Graph but are specific to Twitter.

html
Copy code
<head>
    
    <meta name="twitter:card" content="summary_large_image" />

    
    <meta name="twitter:title" content="Best Hiking Trails in Colorado - Trail Explorer" />

    
    <meta name="twitter:description" content="Explore the most breathtaking hiking trails in Colorado, complete with stunning views and detailed guides." />

    
    <meta name="twitter:url" content="https://www.trailexplorer.com/hiking-trails-colorado" />

    
    <meta name="twitter:image" content="https://www.trailexplorer.com/images/colorado-trail.jpg" />

    
    <meta name="twitter:site" content="@TrailExplorer" />
</head>

**Comment by 0x3mr** [comment]
Added SEO parameters to index.html.
