### ISSUE TITLE
[Backend] Connect MongoDB

### ISSUE THREAD

**Issue by Justxd22** [Justxd22/tic_tac_toe#7]
- Please use pymongo
- Add basic connection code
- Find a free online mongo Host
- Don't forget to add in requirements.txt

**Comment by Justxd22** [comment]
Working on this

**Comment by Justxd22** [comment]
Mongo added, Please help find free online host for mongo

**Comment by 0x3mr** [comment]
Created a new cluster on MongoDB Atlas & connected it successfuly.
